# Generated by Django 2.2.13 on 2021-01-25 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactDate', models.DateField(default=datetime.date.today, unique=True)),
                ('OpeningBalance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('CurrentBalance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('GSTRate', models.IntegerField(choices=[(0, '0'), (5, '5'), (12, '12'), (18, '18')], default=2)),
                ('per', models.CharField(choices=[('e', ''), ('Bottle', 'Bottle'), ('KG', 'KG'), ('Nos', 'NOs'), ('Tin', 'Tin'), ('Packet', 'Packet'), ('Jar', 'Jar'), ('Litre', 'Litre'), ('Box', 'Box')], default='e', help_text='Measurement. Per box/tin/kg', max_length=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='StockInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_date', models.DateField(default=datetime.date.today, unique=True)),
                ('stock_status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='New', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('GSTIN', models.CharField(blank=True, max_length=20)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Ingredients')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.StockInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_date', models.DateField(default=datetime.date.today)),
                ('order_status', models.CharField(choices=[('New', 'New'), ('Received', 'Received'), ('Paid', 'Paid')], default='Received', max_length=20)),
                ('ordered_by', models.CharField(blank=True, default='WC', max_length=80)),
                ('pay_status', models.CharField(choices=[('Fully-Paid', 'Fully-Paid'), ('Partial', 'Partial'), ('Not-Paid', 'Not-Paid')], default='Not-Paid', max_length=20)),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Suppliers')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('unitPrice', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('unitPrice_before_tax', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('unitPrice_tax', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('itemTotal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Ingredients')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Orders')),
            ],
            options={
                'verbose_name': 'Order Details',
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='CashRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Miscellaneous', max_length=50)),
                ('sub_category', models.CharField(default='sub-type', max_length=50, unique=True)),
                ('Type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=6)),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('cashRecordId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.CashRecord')),
            ],
        ),
    ]
