# Generated by Django 2.2.13 on 2020-07-22 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactDate', models.DateField(default=datetime.date.today, unique=True)),
                ('OpeningBalance', models.FloatField(default=0)),
                ('CurrentBalance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CashRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Miscellaneous', max_length=50)),
                ('sub_category', models.CharField(default='sub-type', max_length=50, unique=True)),
                ('Type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=6)),
                ('Amount', models.FloatField(default=0)),
                ('cashRecordId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.CashRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('GSTRate', models.IntegerField(choices=[(0, '0'), (5, '5'), (12, '12'), (18, '18')], default=2)),
                ('per', models.CharField(choices=[('e', ''), ('Bottle', 'Bottle'), ('KG', 'KG'), ('Nos', 'NOs'), ('Tin', 'Tin'), ('Packet', 'Packet'), ('Jar', 'Jar'), ('Litre', 'Litre'), ('Box', 'Box')], default='e', help_text='Measurement. Per box/tin/kg', max_length=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('unitPrice', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('unitPrice_before_tax', models.FloatField(default=0)),
                ('unitPrice_tax', models.FloatField(default=0)),
                ('itemTotal', models.FloatField(default=0)),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_date', models.DateField()),
                ('ordered_by', models.CharField(max_length=80)),
                ('order_total_before_tax', models.FloatField(default=0)),
                ('order_total_after_tax', models.FloatField(default=0)),
                ('gst_tax', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Order',
                'ordering': ['order_status'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('GSTIN', models.CharField(blank=True, max_length=20)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Status'),
        ),
        migrations.AddField(
            model_name='orders',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Suppliers'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Orders'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Status'),
        ),
    ]
