# Generated by Django 2.2.13 on 2020-08-01 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200722_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='trans_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('Order', 'order'), ('Instance', 'instance')], default='order', max_length=20),
        ),
    ]
