# Generated by Django 2.2.13 on 2020-08-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200801_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_by',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
