# Generated by Django 2.2.13 on 2020-08-12 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200812_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinstance',
            name='stock_date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
