# Generated by Django 2.2.13 on 2020-12-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200812_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='gst_tax',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_total_after_tax',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_total_before_tax',
        ),
    ]
