# Generated by Django 2.2.13 on 2020-12-28 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201223_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['order_status'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Received', 'Received')], default='Received', max_length=10),
        ),
    ]
