# Generated by Django 2.2.13 on 2020-12-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201228_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['ordered_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='Received', max_length=10),
        ),
    ]
