# Generated by Django 2.2.13 on 2020-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20201228_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Received', 'Received'), ('Paid', 'Paid')], default='Received', max_length=20),
        ),
    ]
